### ISSUE TITLE
Couldn't find a valid ICU package installed

### ISSUE THREAD

**Issue by securingdev** [X0RW3LL/Minitrue#1]
:wave: Hello! `andMYhacks` here from Kali Linux / Offensive Security Discord :blush: 

First off, thanks for making this tool - having a bare metal Kali Linux machine makes the development of exploitable Word documents for the Penetration Testing with Kali Linux course sort-of tough :sweat_smile: and your project definitely helps with that :blush: 

Anyhow - today I pulled down your project and gave it a try. Unfortunately I encountered an error on Kali Linux 2022.3 after installing both `libgdiplus` the first time around, and `libicu-dev` (which I discovered after Googling the error as a possible solution) the second time around after trying to troubleshoot the issue myself.

The error I'm receiving is in the screenshot below. My best guess is that it has something to do with not having a proper .NET installation on my box. Any guidance you can provide toward a resolution might help others attempting to use the project in the future :bow: I would be happy to help troubleshoot async, or synchronously if you want to try messaging me on Discord :+1: 

![minitrue-error](https://user-images.githubusercontent.com/22803099/199367585-46c00db0-7582-4664-8801-6cb72445af14.png)

**Comment by securingdev** [comment]
For context, the inputs I tried using:
- Payload: windows/shell_reverse_tcp
- Payload type: both (VBA Macro and OLE)
- LHOST=$my_ip
- LPORT= $my_port
- Payload encoder: x86/shikata_ga_nai -i 3

**Comment by X0RW3LL** [comment]
Hi @securingdev :wave: 

Apologies for having closed the issue by mistake, and thanks for bringing this to my attention!

Looks like Aspose.Words depends on libicu63 specifically for unicode/ico support, so we're gonna have to install this manually from the Debian buster repo. I already had the package preinstalled on my Kali setup because I've had this system for about 2 years now, so maybe the package was still in the repos back then, and I also installed various dev dependencies, so that might explain why I already had it.

I can confirm that this is an issue with fresh/newer Kali installs as I tested it on a new instance [2022.3]. I'll walk you through the installation steps, and update the documentation right after.

- Navigate to https://packages.debian.org/buster/amd64/libicu63/download
- Download the libicu63 package using any of the listed mirrors
- Verify the package sha256 checksum
- Install the package

```sh
# Verify sha256 checksum one-liner
# Provided hash is 38f65aaec4ee088f65330cf636c1cd6edef38109c80559836ecf38e2390a5761 at the time of writing this guide, ref: https://packages.debian.org/buster/amd64/libicu63/download

$ [ "$(sha256sum libicu63_63.1-6+deb10u3_amd64.deb | cut -d ' ' -f1)" == "38f65aaec4ee088f65330cf636c1cd6edef38109c80559836ecf38e2390a5761" ] && echo '[+] SHA256 checksum OK' || echo "[-] SHA256 checksum mismatch"

$ sudo apt install ./libicu63_63.1-6+deb10u3_amd64.deb
```

**Comment by securingdev** [comment]
:tada: This resolved the issue :blush: Thanks so much again @X0RW3LL for this excellent tool!
